CREATE TABLE artists (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(60)
);

CREATE TABLE mails (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	owner_name VARCHAR(60),
	mail VARCHAR(60)
);

CREATE TABLE news (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	title VARCHAR(300),
	guid VARCHAR(300),
	pubdate VARCHAR(100),
	description TEXT
);